language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "fkutzner-github"
    token:
      secure: "HBxyKx5j70S0go0geJCv+fpUSYak4NY2z3JIfyyMVdtjz1HkCNlY5FLkVRjIWrUC5/HQP7FcMvjhI53XyXlVg5VgE8iX0YfsdIobuAo8s0LiEvOBjZzo3khNErv3Z8z3Bz4G4aquN9dtZgyDvRaF4vONDmcIXG29LEuEwEpJ6Cot3Xn82p8MgIt2D12LN0bGGdpUpssYrW1r6FbTIMkIOksifbjdsIZj75TUykkPgNHpN/58RE6vizK6gK5oZ4AFji6UuFYbH783KVaXF+rFuOcqHjvBUcEY23tvlkKxNU4hurkD0zNdLqOUK0kHf5w/xxeYaF2LLt0HxsT0IaBYIVncVeOISoZEutSQKA4+i9vNGB6tVJQyGsCkxk+78G+LDnof2pFDk6zimwZeud1cRMJRzZ8Ws5dzZCNAjAT312kIe/afWIw+vrFUJ0rzwiRp37bJGFcsZcSDXocx+UT9XmRa/De3ooMqiYem5rgRnallYr2o1rWa1FGFcvckagg2OG+qZqhNY7Sneiw1FImAVCWA3kSaYnqL68srSq4dyIQkuK/TkM/yH6i27sl9jT28ybyYsGFsI1ueyq7HjCERVojkdLdMCVprOEhrcLuexESfvO40dhsevHjFZ0+D0hljKbLbxEnCqvd7o8QiBQUDZ1ef20B945fIprmJmy9shV4="

env:
  matrix:
    - JAMSAT_MODE=REGULAR
    - JAMSAT_MODE=COVERAGE
    - JAMSAT_MODE=SANITIZERS

matrix:
  include:
    - os: linux
      compiler: gcc
      env: SONARSOURCE_SCAN=1 JAMSAT_MODE=REGULAR
  exclude:
    - os: osx
      env: JAMSAT_MODE=COVERAGE
    - os: osx
      env: JAMSAT_MODE=SANITIZERS
    - os: osx
      compiler: gcc
    - os: linux
      compiler: gcc
      env: JAMSAT_MODE=SANITIZERS
    - os: linux
      compiler: clang
      env: JAMSAT_MODE=COVERAGE

# Note: For clang builds on Linux, a gcc-6 environment is set up as well so that a
# C++14-compliant libstdc++ can be used.
before_script:
  - if [ `uname` = "Linux" ]; then
      wget -nv -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - ;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ;
      sudo add-apt-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main" ;
      sudo apt-get update ;
      sudo apt-get install -y libboost-all-dev ;
      if [ "$CXX" = "g++" ]; then
         sudo apt-get install -y --force-yes g++-6 ;
         export CC=gcc-6 ;
         export CXX=g++-6 ;
      fi ;
      if [ "$CXX" = "clang++" ]; then
         sudo apt-get install -y --force-yes g++-6 ;
         sudo apt-get install -y --force-yes clang-4.0 ;
         export CC=clang-4.0 ;
         export CXX=clang++-4.0 ;
      fi ;
    fi
  - if [ "$JAMSAT_MODE" = "COVERAGE" ]; then
      gem install coveralls-lcov ;
      sudo apt-get install lcov ;
    fi

script:
  - mkdir -p ../build
  - cd ../build
  - bash $TRAVIS_BUILD_DIR/etc/TravisBuild.sh

cache:
  directories:
    - '$HOME/.sonar/cache'
