language: cpp
compiler:
  - gcc
  - clang

os:
  # Having CI for Linux would be super, but the boost binaries provided for
  # Ubuntu Trusty are just too old. Building boost takes too long.
  # - linux
  - osx

git:
  depth: 1

sudo: required

script:
  - mkdir -p ../build
  - cd ../build
  - cmake -DCMAKE_BUILD_TYPE=Debug $TRAVIS_BUILD_DIR
  - cmake --build . -- -j2
  - ctest -V
