image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\repos\JamSAT

platform:
  - x64
  - x86

environment:
  global:
    REPO_DIR: C:\projects\repos
    INSTALLATION_DIR: C:\projects\installation
    BOOST_ROOT: C:\Libraries\boost_1_64_0

configuration:
  - Release
  - Debug

# This is a workaround: AppVeyor tries to directly invoke MSBuild unless
# "build: false" is set, which causes the build script to be ignored.
install:

  - IF "%PLATFORM%" == "x86" ( SET BOOST_LIBRARYDIR=%BOOST_ROOT%/lib32-msvc-15.0)
  - IF "%PLATFORM%" == "x64" ( SET BOOST_LIBRARYDIR=%BOOST_ROOT%/lib64-msvc-15.0)
  - IF "%PLATFORM%" == "x64" ( SET CMAKE_GENERATOR="Visual Studio 15 2017 Win64")
  - IF "%PLATFORM%" == "x86" ( SET CMAKE_GENERATOR="Visual Studio 15 2017")

  # Build zlib (dependency of the JamSAT frontend)
  - cd %REPO_DIR%
  - git clone https://github.com/madler/zlib
  - mkdir zlib-build
  - cd zlib-build
  - cmake -G %CMAKE_GENERATOR% -DCMAKE_INSTALL_PREFIX=%INSTALLATION_DIR% ..\zlib
  - cmake --build . --config %CONFIGURATION% --target install

  # Build Minisat (a testing dependency of JamSAT)
  - cd %REPO_DIR%
  - git clone https://github.com/fkutzner/minisat
  - mkdir minisat-build
  - cd minisat-build
  - cmake -G %CMAKE_GENERATOR% -DONLY_LIBRARIES=ON -DCMAKE_INSTALL_PREFIX=%INSTALLATION_DIR% ..\minisat
  - cmake --build . --config %CONFIGURATION% --target install

  # Build and test JamSAT
  - echo %PLATFORM%
  - echo %BOOST_LIBRARYDIR%
  - set PATH=%PATH%;%BOOST_LIBRARYDIR%
  - cd %REPO_DIR%\JamSAT
  - git submodule init
  - git submodule update
  - mkdir ..\build
  - cd ..\build
  - cmake -G %CMAKE_GENERATOR% -DJAMSAT_LINK_VERBOSE=ON -DCMAKE_INSTALL_PREFIX=%INSTALLATION_DIR% -DCMAKE_PREFIX_PATH=%INSTALLATION_DIR% ..\JamSAT
  - cmake --build . --config %CONFIGURATION%

  - ctest -R testsuite -V -C %CONFIGURATION%
  - ctest -E testsuite -C %CONFIGURATION%

build: false

test: off
